seed: 42
solution: "01001101"
minGenomeLength: 72
maxGenomeLength: 72
maxGeneration: 100000
populationSize: 25

# ELITISM , ROULETTE , TOURNAMENT
selectionStrategy: "TOURNAMENT"
tournamentSize: 4

# PARENTS , CHILDREN , BOTH
mutationTargetStrategy: "CHILDREN"
mutationRate: 0.5
bitFlipRate: 1.0
bitAddRate: 0.0
bitRemoveRate: 0.0

# ONE_POINT , TWO_POINT , UNIFORM , ARITHMETIC
crossoverStrategy: "UNIFORM"
crossoverRate: 0.9

# KEEP_ALL_OR_NOTHING_RANDOMLY , KEEP_ONE_OR_NOT_RANDOMLY , KEEP_ONLY_FROM_FITTEST_PARENT
crossoverLeftoverStrategy: "KEEP_ONE_OR_NOT_RANDOMLY"

# LINEAR, EXPONENTIAL
lengthPunishingStrategy: "EXPONENTIAL"
lengthPunishingFactor: 0.5
