seed: 42
solution: '0110'
minGenomeLength: 72
maxGenomeLength: 72
maxGeneration: 3000
populationSize: 200
tournamentSize: 6
mutationRate: 0.5
bitFlipRate: 1.0
bitAddRate: 0.0
bitRemoveRate: 0.0
crossoverRate: 0.7
lengthPunishingFactor: 0.5
selectionStrategy: ELITISM
mutationTargetStrategy: BOTH
crossoverStrategy: ONE_POINT
crossoverLeftoverStrategy: KEEP_ONLY_FROM_FITTEST_PARENT
lengthPunishingStrategy: LINEAR
